# 公共配置文件
spring:
  application:
    name: backend-template
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xingcheninit
    username: root
    password: 419520
  # Redis 配置
  redis:
    database: 1
    host: 23.224.98.132
    port: 6379
    timeout: 5000
    password: 419520
  # Elasticsearch 配置
  elasticsearch:
    uris: http://23.224.98.132:9200
    username: root
    password: 419520
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # 统一配置返回时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  mp:
    token: xingchen
    aesKey: qrtyguCCAAValMqOWmvou5pvMKH9ZERklLfit2z6fUe
    appId: wx5de2adad299dbb8a
    secret: 9651c497c0b8978f667c72c0cc3f3e19
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 阿里云对象存储（至少需要配置为公共读）
oss:
  client:
    accessKey: LTAI5tFB358NsF47yqMggYHC
    secretKey: 1BHLgaf5THQFrLwXxp7daZa3ALDibY
    region: oss-cn-shanghai.aliyuncs.com
    bucket: xingchenmeng