# 线上配置文件
# @author 观止study
#  @from https://blog.csdn.net/m0_66570338/article/details/132145086
server:
  port: 8101
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xingcheninit
    username: root
    password: 419520
  # Redis 配置
  redis:
    database: 1
    host: 23.224.98.132
    port: 6379
    timeout: 5000
  # Elasticsearch 配置
  elasticsearch:
    uris: http://23.224.98.132:9200
    username: root
    password: 419520
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''